import mongoose from 'mongoose'
import validator from 'validator' //https://www.npmjs.com/package/validator

function validateURL(value: string) {
    return validator.isURL(value, { require_tld: false })
}

export interface Team extends mongoose.Document {
     //_id: Pretty sure _id is autogenerated...
     projectId : string
     teamMembers : string[]
}

const TeamSchema = new mongoose.Schema<Team>({
    projectId: {
        type: String,
        required: [true, 'Please tell us the project_id for this team'],
        maxlength: [30, 'Name cannot be more than 30 characters'],
      },
    teamMembers:{
        type: [String]
    },
})

export default mongoose.models.Team || mongoose.model<Team>('Team', TeamSchema)